/**
 * Load environment variables, then derive slot-specific ports.
 *
 * Effective precedence (highest first):
 *   1. .env.local — personal escape hatch, loaded with override: true so it
 *      beats even variables injected into the process env (e.g. by
 *      `infisical run`). Gitignored. Use for deliberate local overrides only;
 *      set DEV_PORT_OFFSET=0 here to disable slot derivation if you override
 *      a port with its final value.
 *   2. Injected process env — `infisical run` (team dev) or the shell.
 *   3. .env.dev — generated by ./dev; carries DEV_PORT_OFFSET for the slot.
 *   4. .env — fallback for contributors without Infisical access.
 *
 * dotenv never overwrites a variable that is already set, which yields the
 * order above; .env.local jumps the queue via override: true. Afterwards
 * applyDevPortOffset() shifts port variables and localhost URLs by
 * DEV_PORT_OFFSET (no-op when unset).
 *
 * Import this as the very first thing in every entry point:
 *   import './config/env';      // main.ts, cli/main.ts
 *   import 'src/config/env';    // seed scripts (with tsconfig-paths)
 */
import { config } from 'dotenv';
import { applyDevPortOffset } from './dev-port-offset';

// quiet: true suppresses the dotenv v17 promotional console message.
config({ path: '.env.local', override: true, quiet: true });
config({ path: '.env.dev', quiet: true });
config({ path: '.env', quiet: true });
applyDevPortOffset();
