/**
 * Load environment variables from .env.dev (if present) and .env.
 *
 * .env.dev is generated by the ./dev script with per-slot connection config
 * (localhost hosts, offset ports). It takes precedence over .env for any
 * variable it defines. .env fills in everything else (secrets, app config).
 *
 * Import this as the very first thing in every entry point:
 *   import './config/env';      // main.ts, cli/main.ts
 *   import 'src/config/env';    // seed scripts (with tsconfig-paths)
 *
 * Or preload it for CLI tools:
 *   ts-node -r tsconfig-paths/register -r src/config/env-register ./node_modules/typeorm/cli.js
 */
import { config } from 'dotenv';

// Load .env.dev first (if present), then .env. Dotenv won't overwrite
// vars already set, so .env.dev values take precedence.
config({ path: '.env.dev' });
config({ path: '.env' });
