export enum SourceProcessingErrorCode {
  DOCUMENT_UNREADABLE = 'DOCUMENT_UNREADABLE',
  DOCUMENT_EMPTY = 'DOCUMENT_EMPTY',
  DOCUMENT_PAGE_LIMIT_EXCEEDED = 'DOCUMENT_PAGE_LIMIT_EXCEEDED',
  PROCESSING_TIMEOUT = 'PROCESSING_TIMEOUT',
  PROCESSING_UNAVAILABLE = 'PROCESSING_UNAVAILABLE',
  PROCESSING_FAILED = 'PROCESSING_FAILED',
}
