export const TOUR_TARGET = {
  configureModelsLanguage: 'configure-models-language',
  inviteUsers: 'invite-users',
  createTeam: 'create-team',
  addTeamMember: 'add-team-member',
  chatUpload: 'chat-upload',
  anonymousMode: 'anonymous-mode',
  voiceInput: 'voice-input',
  modelSelector: 'model-selector',
  createSkill: 'create-skill',
  createKnowledgeBase: 'create-knowledge-base',
  addDocuments: 'add-documents',
  systemPrompt: 'system-prompt',
  themeSettings: 'theme-settings',
  sendMessage: 'send-message',
  createWorkspace: 'create-workspace',
  favoriteWorkspace: 'favorite-workspace',
  chatComposer: 'chat-composer',
  selectWorkspaceInChat: 'select-workspace-in-chat',
  assignChatToWorkspace: 'assign-chat-to-workspace',
  workspaceInstruction: 'workspace-instruction',
  workspaceKnowledge: 'workspace-knowledge',
  workspaceSkill: 'workspace-skill',
} as const;

export type TourTargetName = (typeof TOUR_TARGET)[keyof typeof TOUR_TARGET];
