import { createAjv } from 'src/common/validators/ajv.factory';
import { formatAjvErrors } from 'src/common/validators/tool-params.validator';
import { ToolType } from '../value-objects/tool-type.enum';
import type { FromSchema, JSONSchema } from 'json-schema-to-ts';
import { Tool } from '../tool.entity';
import { ToolExecutionFailedError } from '../../application/tools.errors';

const generateImageToolParameters = {
  type: 'object' as const,
  properties: {
    prompt: {
      type: 'string' as const,
      description: 'A detailed text description of the image to generate',
      maxLength: 4000,
    },
    size: {
      type: 'string' as const,
      enum: ['auto', 'square', 'landscape', 'portrait'] as const,
      description:
        "The aspect ratio of the generated image. Choose the ratio that best fits the content so it is not cropped: 'landscape' for wide content such as flow charts, diagrams, banners or scenery; 'portrait' for tall content such as posters or full-body figures; 'square' for icons, avatars or balanced compositions. Use 'auto' (the default) to let the model pick the best ratio for the prompt.",
    },
    use_uploaded_images: {
      type: 'boolean' as const,
      description:
        'Set to true whenever the request is based on an image the user uploaded in this conversation (recreate, redraw, restyle, or closely reproduce it). The uploaded images are then passed to the image model directly as visual references, which preserves detail far better than any text description. Still write a prompt describing the desired output.',
    },
    reference_generated_image_ids: {
      type: 'array' as const,
      items: {
        type: 'string' as const,
        format: 'uuid' as const,
      },
      maxItems: 16,
      description:
        'IDs of images previously generated by this tool in this conversation, to pass to the image model as visual references. Use for iterative refinement of a generated image (e.g. "make the dog bigger") so the model edits the actual image instead of regenerating it from text.',
    },
  },
  required: ['prompt'],
  additionalProperties: false,
} as const satisfies JSONSchema;

type GenerateImageToolParameters = FromSchema<
  typeof generateImageToolParameters
>;

export class GenerateImageTool extends Tool {
  constructor() {
    super({
      name: ToolType.GENERATE_IMAGE,
      description:
        'Generate an image from a text description, optionally using images from the conversation as visual references. Returns a unique image ID that references the generated image.',
      descriptionLong:
        'Use when the user asks you to create, draw, design, or generate an image, illustration, diagram, or visual content. When the request is based on an image the user uploaded, set use_uploaded_images so the image model sees the original instead of a text description. When refining an image generated earlier, pass its ID in reference_generated_image_ids. The tool returns an image ID; you do not need to display the image yourself as it will be rendered automatically.',
      parameters: generateImageToolParameters,
      type: ToolType.GENERATE_IMAGE,
    });
  }

  // Throws ToolExecutionFailedError directly (not a plain Error like the
  // other entities): the handler's error boundary would otherwise replace
  // the validation detail with its generic image-generation message.
  validateParams(params: Record<string, unknown>): GenerateImageToolParameters {
    const ajv = createAjv({ allErrors: true });
    const validate = ajv.compile(this.parameters);
    if (!validate(params)) {
      throw new ToolExecutionFailedError({
        toolName: this.name,
        message: formatAjvErrors(validate.errors ?? []),
        exposeToLLM: true,
      });
    }
    return params as GenerateImageToolParameters;
  }

  get returnsPii(): boolean {
    return false;
  }
}
