stages:
  - lint
  - deploy

# LINT
eslint:
  stage: lint
  image: node:20
  script:
    - npm ci
    - npm run lint

# DEPLOY
build-and-push-to-registry:
  stage: deploy
  only:
    refs:
      - master
  image: docker:28.3.3-dind
  services:
    - name: docker:28.3.3-dind
      alias: docker
  script:
    - echo -n $CONTAINER_REGISTRY_PASSWORD | docker login -u docker --password-stdin ${CONTAINER_REGISTRY}
    - echo "Building Image for ${PWD##*/} with tag latest for ${CONTAINER_REGISTRY}"
    - docker build . -t ${CONTAINER_REGISTRY}/${PWD##*/}:latest && docker push ${CONTAINER_REGISTRY}/${PWD##*/}:latest