#!/usr/bin/env bash
# Shared helpers for the Cursor Cloud Agent environment (sourced by
# install.sh and start.sh). Provisions native Postgres+pgvector, Redis and
# MinIO on localhost — no Docker. See .cursor/README.md for rationale.

# Resolve repo root (this file lives in <repo>/.cursor/).
REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
export REPO_DIR

export PGDATA="${PGDATA:-/data/pg}"
export PGHOST=localhost
export PGPORT=5432
export MINIO_DATA="${MINIO_DATA:-/data/minio}"

# Postgres server binaries (initdb, pg_ctl, pg_isready, …) live in a versioned
# dir that isn't on the default PATH. A Dockerfile `ENV PATH=…` can't help here:
# Cursor's runtime shell doesn't inherit the image ENV, and `runuser` resets
# PATH for the target user anyway — so resolve the dir explicitly here and
# prepend it to PATH.
PG_BIN=""
for _d in $(ls -d /usr/lib/postgresql/*/bin 2>/dev/null | sort -V); do
  [ -x "$_d/initdb" ] && PG_BIN="$_d"
done
if [ -n "$PG_BIN" ]; then
  export PATH="$PG_BIN:$PATH"
fi
export PG_BIN

# Postgres refuses to run as root, so when we're root we drive it as the
# `postgres` system user (created by the postgresql-16 package). Otherwise we
# run everything as the current (non-root) user. In the root case we forward
# PATH through `runuser` (which otherwise resets it) so the postgres user can
# still resolve the server binaries.
if [ "$(id -u)" = "0" ]; then
  PG_RUN_USER=postgres
  run_pg() { runuser -u "$PG_RUN_USER" -- env "PATH=$PATH" "$@"; }
else
  PG_RUN_USER="$(id -un)"
  run_pg() { "$@"; }
fi
export PG_RUN_USER

cluster_initialized() { [ -s "$PGDATA/PG_VERSION" ]; }

init_cluster() {
  echo "==> Initializing Postgres cluster at $PGDATA (owner: $PG_RUN_USER)"
  if [ "$(id -u)" = "0" ]; then
    mkdir -p "$PGDATA" && chown "$PG_RUN_USER" "$PGDATA" && chmod 700 "$PGDATA"
  else
    mkdir -p "$PGDATA" && chmod 700 "$PGDATA"
  fi
  # trust auth on localhost only — fine for a throwaway single-tenant dev VM.
  run_pg initdb -D "$PGDATA" --auth=trust --username=postgres --encoding=UTF8
}

pg_running() { run_pg pg_ctl -D "$PGDATA" status >/dev/null 2>&1; }

pg_start() {
  pg_running && return 0
  echo "==> Starting Postgres"
  # Point the Unix socket dir at $PGDATA: Debian's compiled default
  # (/var/run/postgresql) lives on tmpfs and can be absent on a fresh boot,
  # which makes the server fail to start. Clients connect over TCP
  # (-h localhost), so the socket location is irrelevant to them.
  run_pg pg_ctl -D "$PGDATA" -w -l "$PGDATA/server.log" \
    -o "-c listen_addresses=localhost -p $PGPORT -c unix_socket_directories=$PGDATA" start
}

pg_stop() {
  pg_running || return 0
  echo "==> Stopping Postgres"
  run_pg pg_ctl -D "$PGDATA" -m fast -w stop || true
}

# Create the app database + pgvector extension (idempotent).
bootstrap_db() {
  run_pg createdb -h "$PGHOST" -p "$PGPORT" -U postgres ayunis 2>/dev/null || true
  run_pg psql -h "$PGHOST" -p "$PGPORT" -U postgres -d ayunis \
    -c 'CREATE EXTENSION IF NOT EXISTS vector;' >/dev/null
}

# Write ayunis-core-backend/.env for native-localhost services. Idempotent:
# preserves generated secrets across re-runs; injects provider keys from the
# environment (Cursor Secrets) when present.
write_env() {
  local env_file="$REPO_DIR/ayunis-core-backend/.env"
  local mcp jwt cookie
  mcp="$(grep -E '^MCP_ENCRYPTION_KEY=' "$env_file" 2>/dev/null | cut -d= -f2- || true)"
  jwt="$(grep -E '^JWT_SECRET=' "$env_file" 2>/dev/null | cut -d= -f2- || true)"
  cookie="$(grep -E '^COOKIE_SECRET=' "$env_file" 2>/dev/null | cut -d= -f2- || true)"
  [ -n "$mcp" ] || mcp="$(openssl rand -hex 32)"
  [ -n "$jwt" ] || jwt="$(openssl rand -hex 32)"
  [ -n "$cookie" ] || cookie="$(openssl rand -hex 32)"

  echo "==> Writing $env_file"
  cat > "$env_file" <<EOF
# Auto-generated by .cursor/install.sh for Cursor Cloud Agents.
# Native localhost services (Postgres/Redis/MinIO) — no Docker.
# Do not commit; regenerated on each environment build.
NODE_ENV=development
APP_ENVIRONMENT=self-hosted
PORT=3000

# Postgres (trust auth on localhost)
POSTGRES_HOST=localhost
POSTGRES_PORT=5432
POSTGRES_USER=postgres
POSTGRES_PASSWORD=postgres
POSTGRES_DB=ayunis

# Redis
REDIS_HOST=localhost
REDIS_PORT=6379

# MinIO
MINIO_ENDPOINT=localhost
MINIO_PORT=9000
MINIO_USE_SSL=false
MINIO_ROOT_USER=minio
MINIO_ROOT_PASSWORD=minio123
MINIO_ACCESS_KEY=minio
MINIO_SECRET_KEY=minio123
MINIO_BUCKET=ayunis

# Frontend / CORS / cookies (http, not https)
FRONTEND_BASEURL=http://localhost:3001
CORS_ALLOWED_ORIGINS=http://localhost:3001,http://localhost:3000
COOKIE_SECURE=false
COOKIE_SAME_SITE=lax
COOKIE_DOMAIN=localhost

# Self-host: allow the seeded org to work end-to-end
DISABLE_REGISTRATION=false

# Secrets (generated once, preserved across idempotent re-runs)
MCP_ENCRYPTION_KEY=$mcp
JWT_SECRET=$jwt
COOKIE_SECRET=$cookie

# Provider API keys — injected from Cursor Secrets if set (needed for inference)
OPENAI_API_KEY=${OPENAI_API_KEY:-}
ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY:-}
MISTRAL_API_KEY=${MISTRAL_API_KEY:-}
GEMINI_API_KEY=${GEMINI_API_KEY:-}
EOF
}

run_migrations() {
  echo "==> Running database migrations"
  ( cd "$REPO_DIR/ayunis-core-backend" && pnpm run migration:run:dev )
}

run_seed() {
  echo "==> Seeding database (idempotent)"
  # seed:ts is find-or-create; non-fatal so a partial seed never blocks boot.
  ( cd "$REPO_DIR/ayunis-core-backend" && pnpm run seed:ts ) \
    || echo "   seed skipped/failed (non-fatal)"
}

start_redis() {
  redis-cli ping >/dev/null 2>&1 && return 0
  echo "==> Starting Redis"
  redis-server --daemonize yes
}

start_minio() {
  curl -fsS http://localhost:9000/minio/health/live >/dev/null 2>&1 && return 0
  echo "==> Starting MinIO"
  mkdir -p "$MINIO_DATA"
  MINIO_ROOT_USER=minio MINIO_ROOT_PASSWORD=minio123 \
    nohup minio server "$MINIO_DATA" --address :9000 --console-address :9001 \
    > /tmp/minio.log 2>&1 &
}

wait_infra() {
  echo "==> Waiting for Postgres + MinIO to become ready"
  local i
  for i in $(seq 1 30); do
    run_pg pg_isready -h localhost -p 5432 >/dev/null 2>&1 && break
    sleep 1
  done
  for i in $(seq 1 30); do
    curl -fsS http://localhost:9000/minio/health/live >/dev/null 2>&1 && break
    sleep 1
  done
}
