/** !!These types are also used as tool names!! */
export enum ToolType {
  HTTP = 'http',
  SOURCE_QUERY = 'source_query',
  SOURCE_GET_TEXT = 'source_get_text',
  INTERNET_SEARCH = 'internet_search',
  WEBSITE_CONTENT = 'website_content',
  SEND_EMAIL = 'send_email',
  CREATE_CALENDAR_EVENT = 'create_calendar_event',
  CODE_EXECUTION = 'code_execution',
  BAR_CHART = 'bar_chart',
  LINE_CHART = 'line_chart',
  PIE_CHART = 'pie_chart',
  MCP_TOOL = 'mcp_tool',
  MCP_RESOURCE = 'mcp_resource',
  MCP_PROMPT = 'mcp_prompt',
  PRODUCT_KNOWLEDGE = 'product_knowledge',
  ACTIVATE_SKILL = 'activate_skill',
  CREATE_SKILL = 'create_skill',
  KNOWLEDGE_QUERY = 'knowledge_query',
  KNOWLEDGE_GET_TEXT = 'knowledge_get_text',
  CREATE_DOCUMENT = 'create_document',
  UPDATE_DOCUMENT = 'update_document',
}
