export enum PlatformConfigKey {
  CREDITS_PER_EURO = 'CREDITS_PER_EURO',
  FAIR_USE_LOW_LIMIT = 'FAIR_USE_LOW_LIMIT',
  FAIR_USE_LOW_WINDOW_MS = 'FAIR_USE_LOW_WINDOW_MS',
  FAIR_USE_MEDIUM_LIMIT = 'FAIR_USE_MEDIUM_LIMIT',
  FAIR_USE_MEDIUM_WINDOW_MS = 'FAIR_USE_MEDIUM_WINDOW_MS',
  FAIR_USE_HIGH_LIMIT = 'FAIR_USE_HIGH_LIMIT',
  FAIR_USE_HIGH_WINDOW_MS = 'FAIR_USE_HIGH_WINDOW_MS',
}
